### ISSUE TITLE
new YML syntax; the older one will be removed on 31th september 2019

### ISSUE THREAD

**Issue by tristanbes** [hmarr/auto-approve-action#10]
> GitHub Actions now uses YAML syntax in workflow files. **Support for the HCL syntax in GitHub Actions will be deprecated on September 30, 2019**. To continue using workflows that you created with the HCL syntax, you'll need to migrate the workflow files to the new YAML syntax using the migration script.

See: https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax#about-the-new-yaml-syntax-for-github-actions

**Comment by tristanbes** [comment]
ping @hmarr we're getting errors from this when used in a `YML`syntax; is this linked ? 

```
------------------------------
The reported error code : 
### ERRORED 12:55:50Z
- There was an unexpected error when executing this Action. For help debugging what went wrong, please contact support@github.com. The unique ID for this error is E993:0170:149D8:46A7C:5D779D38
------------------------------
```


The source `.workflow` file :

```
workflow "Auto Approve" {
  on = "pull_request"
  resolves = ["hmarr/auto-approve-action"]
}
action "Filters for GitHub Actions" {
  uses = "actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da"
  args = ["actor", "dependabot-preview[bot]", "dependabot[bot]"]
}
action "hmarr/auto-approve-action" {
  uses = "hmarr/auto-approve-action@master"
  needs = ["Filters for GitHub Actions"]
  secrets = ["GITHUB_TOKEN"]
}
```

------------------------------

The generated .yml file :

```yml
on: pull_request
name: Auto Approve
jobs:
  filtersForGitHubActions:
    name: Filters for GitHub Actions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filters for GitHub Actions
      uses: actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da
      with:
        args: actor dependabot-preview[bot] dependabot[bot]
    - name: hmarr/auto-approve-action
      uses: hmarr/auto-approve-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
