### ISSUE TITLE
I actually ran into this same issue... and "fixing" it (step 1 below) caused a more dangerous issue that I fortunately caught pretty quickly (step 2 below).

### ISSUE THREAD

**Issue by payang04** [hmarr/auto-approve-action#105]
I actually ran into this same issue... and "fixing" it (step 1 below) caused a more dangerous issue that I fortunately caught pretty quickly (step 2 below).

1. Add *the user that owns the `GITHUB_TOKEN` your are using for the workflow* to your `CODEOWNERS` file like so:

    ```config
    package.json @token-user
    yarn.lock @token-user
    ```
2. Ensure that only pull requests marked for automatic merge get approvals:

   ```yaml
   - uses: hmarr/auto-approve-action@v2.0.0
     if:
       (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
       && contains(github.event.pull_request.body, 'will automatically merge')
   ```

---

⚠️ Important: make sure you add the `contains(github.event.pull_request.body, 'will automatically merge')` condition, otherwise @dependabot-preview will merge all pull requests that it opens because they all receive an approval from a code owner without that condition.

@hmarr it might be worth adding this information to the `README`, let me know if you'd like me to open a PR to do so!

_Originally posted by @jrolfs in https://github.com/hmarr/auto-approve-action/issues/93#issuecomment-604690382_
