### ISSUE TITLE
Auto Approve code owners.

### ISSUE THREAD

**Issue by UdhavPawar** [hmarr/auto-approve-action#146]
Hello, hope you are doing great.

- Thank you for this awesome workflow action :)
- My aim is: **when a PR is submitted by bot, it should be auto-approved by code-owner and not github-action**s.
- PR from bot is identified using `github.actor`.
- Followed README and setup following action:
```
name: Auto approve

on:
  pull_request

jobs:        
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: (github.actor == 'awsgitbot' || github.actor == 'awsgitbot')
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
```
- auto-approve works as expected, but the approval is done by github-actions and not by code owner.
- when the condition is updated to: `(github.actor == 'awsgitbot' || github.actor == 'awsgitbot') && contains(github.event.pull_request.body, 'will automatically merge')`, no approval is performed.
- please lmk if any other info is needed and guide me on same. appreciate your help and time.
