### ISSUE TITLE
GITHUB_TOKEN read-only breaks github action

### ISSUE THREAD

**Issue by chrisgilmerproj** [hmarr/auto-approve-action#183]
See #180 for some details on this issue.

March 1st, Github changed the `GITHUB_TOKEN` to be read-only for all workflows. [See the announcement dated Feb 19, 2020](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/). This has to do with security vulnerabilities with using the `pull_request_target` trigger and scoping permissions. [See guide on Preventing Pwn Requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests). 

Unfortunately this breaks the integration as seen here:

<img width="416" alt="Screen Shot 2021-03-10 at 9 51 19 AM" src="https://user-images.githubusercontent.com/219296/110674182-7f85ad80-8186-11eb-9382-802611c83d16.png">

Changing the trigger to `pull_request` does not fix it because `write` permissions are needed to create a review of the PR.

While I don't have a solution for fixing this I have reconfigured my job to look like this per the security guidelines, primarily using labels:

```yml
name: auto approve
on:
  pull_request_target:
    types: [labeled]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
```

I want to thank @skjnldsv and @alexwilson for having provided the context I needed to dig into this.
