### ISSUE TITLE
Problems with github token

### ISSUE THREAD

**Issue by robinjhector** [hmarr/auto-approve-action#187]
Hi, I'm getting this error when attempting to run auto-approve for dependabot PRs. The full workflow:

```yml
name: "Auto approve Dependabot updates"

on: pull_request

jobs:
  approve:
    name: Auto approve dependabot pull requests
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
```

The `GITHUB_TOKEN` secret is the default actions token.
But I'm getting the following output:

```
Run hmarr/auto-approve-action@v2
  with:
    github-token: ***
Creating approving review for pull request #51
Error: Resource not accessible by integration. In some cases, the GitHub token used for actions triggered from `pull_request` events are read-only, which can cause this problem. Switching to the `pull_request_target` event typically resolves this issue.
```

I seem to remember this working before. Not sure what has changed. Any ideas?
