### ISSUE TITLE
Duplicate approvals

### ISSUE THREAD

**Issue by JacobHayes** [hmarr/auto-approve-action#213]
After making a change to an approved path, every subsequent commit triggers a new approval. The logs say it is looking for existing reviews, but seems to not find the last one.

<img width="640" alt="Screenshot 2023-02-28 at 19 17 13" src="https://user-images.githubusercontent.com/2555532/222012764-e48a0ab4-061e-462d-9973-878b5aed2d64.png">

Logs from the second run:
```
Fetching user, pull request information, and existing reviews
Current user is github-actions[bot]
Commit SHA is AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Pull request #123 has not been approved yet, creating approving review
Approved pull request #123
```
workflow config:
```
name: Auto approval
on:
  pull_request:
    branches:
      - main
    paths:
      - 'some-dir/**'
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Automatic approval of ..."
```

---

Perhaps there's a missing permission that is preventing it from fetching existing reviews?
