### ISSUE TITLE
Only 1st stale review is refreshed

### ISSUE THREAD

**Issue by kroussou** [hmarr/auto-approve-action#215]
Hi!
Looks like there is an issue with refreshing stale reviews when there is more than one. Only 1st stale review is refreshed in this case. So it is not possible to approve PR automatically if 2 or more reviews is required by branch protection rules.

Example config:
```
      - name: Add approval 1
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.TOKEN1 }}

      - name: Add approval 2
        uses: hmarr/auto-approve-action@v3
```

Steps to reproduce:
1. Create workflow with steps above
2. Wait for approvals and then push another commit to dismiss initial reviews

Actual behavior:
Only one review refreshed

Expected behavior:
All reviews refreshed
