### ISSUE TITLE
Support auto approving based on a string pattern in PR title

### ISSUE THREAD

**Issue by pkgajulapalli** [hmarr/auto-approve-action#228]

**Comment by jsoref** [comment]
This action just does the approval. If you want to do something like this, you just need to write a workflow that does what you want.

Here's an untested workflow that might do what you want (and might also result in someone taking over your repository, please don't trust the words of random people without actually understanding everything that they're suggesting):

```yml
name: Conditional Approval
on:
  pull_request:
    types:
    - created
    - edited
    - reopened
  
jobs:
  approve:
    permissions:
      pull-requests: write
    if: contains(github.event.pull_request.title, '[RUBBER-STAMP]')
    name: Approve
    runs-on: ubuntu-latest
    steps:
    - name: Approve
      uses: hmarr/auto-approve-action@v4
```
