### ISSUE TITLE
Do not auto approve if at least one file does not match the path

### ISSUE THREAD

**Issue by sankettyro** [hmarr/auto-approve-action#42]
We have a requirement where we do not want to auto-approve PR if at least one modified file in the PR does not match the `path` for which the Github action is defined.

For example, considering following directory structure:
```
- dev
   |- deployment.yml 
- prd
   |- deployment.yml
```
We want all changes into `dev` directory to be auto-approved. But does not want to auto-approve any changes into `prd`.

We have following workflow action configured:

```
name: Auto Approve
on:
  pull_request:
    paths:
      - 'dev/**'
      - '!prd/**'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
```
This works fine when we have changes either in the `dev` directory or in the `prd` directory. But when we have changes in both `dev` and `prd` directory then also it auto-approves as there is at least one file in the PR which matches the `path`.

This seems expected as per the documentation for [path](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths)

I was wondering if we can do anything on the action to block auto-approve if at least one file does not match the `path`.

**Comment by hmarr** [comment]
You've probably found a solution by now :-) But in case not, you could try adding step before the auto-approve step that checks the files that were modified and fails accordingly. A failing step will cause future steps to not be run.

**Comment by SharkofMirkwood** [comment]
For anyone else looking for a solution, this separate Action used in conjunction with `auto-approve-action` helped in my case https://github.com/tj-actions/changed-files

For example:

```
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files from specific directories
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:  
          files: |
            my-dir/my-file.txt
            my-other-dir/**
      - name: Auto-approve PR if only a subset of the files listed above have changed
        if: steps.changed-files.outputs.only_changed == 'true'
        uses: hmarr/auto-approve-action@v3
      - if: steps.changed-files.outputs.only_changed != 'true'
        run: echo "Changes detected outside of approved files. Not auto-approving PR."
```
