### ISSUE TITLE
github action not being triggered

### ISSUE THREAD

**Issue by kilianc** [hmarr/auto-approve-action#84]
Hi I am trying to automate all `dependabot` PRs but the action does not appear to be triggered. The `actor` for the PRs is a user in our team (me or another eng).

We removed the `if` condition and just assumed all branches with `dependabot/` as prefix could be safely approved (it's a private repo).

This seems to have no effect

```yml
name: Auto approve

on:
  pull_request:
    branches:
    - "dependabot/**"

jobs:
  approve:
    name: Auto-approve dependabot PRs
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
```

**Comment by hmarr** [comment]
Hi there, I'm afraid I don't follow. Can you clarify what you mean by "the actor for the PRs is a person in our team" and "we removed the conditional"?

Are you using the configuration you pasted in the issue, but finding the Action never gets triggered? If so, what's the name of the bot user that's creating the Dependabot pull request? It should be `dependabot`, `dependabot-preview`, or something else if you're wrapping dependabot-core and running it yourself.

**Comment by kilianc** [comment]
We're using vanilla `dependabot`, no wrappers. The user is indeed `dependabot`and `dependabot-preview`.

Nothing shows up in the actions panel with the above config at the moment :/

**Comment by hazcod** [comment]
Not sure if related, but my dependabot PRs aren't being merged as wel: https://github.com/ironPeakServices/iron-argo/pull/21

**Comment by kilianc** [comment]
Turns out, removing the `branches` filter makes the action run correctly. Maybe the API changed?

**Comment by kilianc** [comment]
The following example works!

```yml
name: Autoapprove

on:
  pull_request:

jobs:
  autoapprove:
    name: Autoapprove dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: ${{ secrets.AUTOAPPROVE_TOKEN }}
```
