### ISSUE TITLE
Codeowner required reviews

### ISSUE THREAD

**Issue by timmyers** [hmarr/auto-approve-action#93]
Is there any way to make this satisfy the "Require review from codeowners" branch protection rule?

I tried adding the user `github-actions` to the CODEOWNERS file for the dependency files (i.e. package.json, yarn.lock), but unfortunately that does not seem to work.

I'm hoping there is some way I can require a review from a codeowner in general, but allow this action's approval to be sufficient for dependency PR's.

**Comment by jrolfs** [comment]
I actually ran into this same issue... and "fixing" it (step 1 below) caused a more dangerous issue that I fortunately caught pretty quickly (step 2 below).

1. Add *the user that owns the `GITHUB_TOKEN` your are using for the workflow* to your `CODEOWNERS` file like so:

    ```config
    package.json @token-user
    yarn.lock @token-user
    ```
2. Ensure that only pull requests marked for automatic merge get approvals:

   ```yaml
   - uses: hmarr/auto-approve-action@v2.0.0
     if:
       (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
       && contains(github.event.pull_request.body, 'will automatically merge')
   ```

---

⚠️ Important: make sure you add the `contains(github.event.pull_request.body, 'will automatically merge')` condition, otherwise @dependabot-preview will merge all pull requests that it opens because they all receive an approval from a code owner without that condition.

@hmarr it might be worth adding this information to the `README`, let me know if you'd like me to open a PR to do so!
